#!/bin/sh

#PHYSIC_IPV6_DEVICE="eth0"
DHCP_CLIENT_DEVICE="lw4over6"

LOCAL_IPV6_ADDR="2001:da8:bf:19::7"
REMOTE_IPV6_ADDR="2001:da8:bf:19::3"

CURDIR=$(pwd)

#cd cpe/tunnel
./cpe/load $REMOTE_IPV6_ADDR $LOCAL_IPV6_ADDR
#cd $CURDIR

nohup ./cra/cra -a $LOCAL_IPV6_ADDR $REMOTE_IPV6_ADDR &

echo "dhcpcd!!!"
./dhcpcd/dhcpcd $DHCP_CLIENT_DEVICE
