#!/bin/bash
 
#-------------------------------------------------------
echo Loading 4over6 module...
insmod lw4over6.ko
ifconfig 4over6 up
ip addr add 58.205.200.1/24 dev 4over6

sysctl net.ipv4.ip_forward=1
#-------------------------------------------------------

iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1420



